---
title: "Outline"
subtitle: "Videoserie Mehrebenenregression"
author: "Dr. Uwe Remer"
date: "Juli 2022"
output:
  html_document:
    toc: yes
    number_sections: yes
    toc_depth: 2
    toc_float:
      collapsed: true
    df_print: paged
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
# Figure size in inches
w = 5
h = 2.5
s = 2.8
    
knitr::opts_chunk$set(eval=TRUE, echo = FALSE, message = FALSE, warning = FALSE,
                      fig.width=w, fig.height=h, fig.align='center')
save <-  F
save_fig <- function(filename, save = TRUE){
  if(save==TRUE){
    ggsave(paste0("./Grafiken/", filename), 
         width = w, height = h,
         #scale = s,       
         unit = "in")
  }
  else{
    message("Saving skipped...")
  }
}
```


# „Was ist eine Mehrebenenregression?“

- dass Sie die unterschiedlichen Bezeichnungen der Mehrebenenregression kennen.
- dass Sie das Grundprinzip der Mehrebenenregression erläutern können.
- dass Sie wissen, welche unterschiedlichen Varianten der Mehrebenenregression es gibt.
- dass Sie entscheiden können, für welche Fragestellungen welche Variante der Mehrebenenregression geeignet sind.




# „Wann ist eine Mehrebenenregression angebracht?“ 

- theoretisch begründen können wie und warum der Kontext einen Einfluss auf Ihre Datenstruktur hat
- erläutern können, was ein Nullmodell ist. und wo dort was Varianzkomponenten sind und wo diese in der Regrgressionsgleichung zu finden sind

- wissen was der Intraklassenkorrelation ICC ist
- wie man den ICC mit R berechnet
- wie der ICC im hinblick auf die Merhebenenregression interpretiert wird 



# „Wie schätzt man eine Mehrebenenregression in R?“

Daten einlesen

- notwendigkeit des Zentrierens
- Wie man die theoretischen Überlegungen zu variirenden Intercepts und variierenden Slopes und Cross-Level Interaktionen mit R modelliert
- welche quantities of interest wichtig sind und wie sie interpretiert werden


# „Wie findet man das passende Modell für die Mehrebenenregression?“ 


# „Wie lassen sich die Ergebnisse einer Mehrebenregression berichten?“




# „Warum ist die Mehrebenenregression das bessere Modell?"

- dass Sie erläutern können, worin sich eine Mehrebenenregression von einer einfachen linearen Regression unterscheidet.
- dass Sie aufzählen können, welche Vorteile eine Mehrebenenregression hat.