<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de-DE" xml:lang="de-DE"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.258">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Uwe Remer">

<title>Mehrebenenregression mit R - 4. Wie schätzt man eine Mehrebenenregression in R?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Mehrebenenregression mit R">
<meta property="og:description" content="6-teilige Videoreihe zum Einstieg in die Mehrebenenregression mit R">
<meta property="og:image" content="Grafiken/varianten.png">
<meta property="og:site-name" content="Mehrebenenregression mit R">
<meta property="og:locale" content="de_DE">
<meta name="twitter:title" content="Mehrebenenregression mit R">
<meta name="twitter:description" content="6-teilige Videoreihe zum Einstieg in die Mehrebenenregression mit R">
<meta name="twitter:image" content="Grafiken/varianten.png">
<meta name="twitter:creator" content="@uweremerbollow">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Mehrebenenregression mit R</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Startseite</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-skript" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Skript</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-skript">    
        <li>
    <a class="dropdown-item" href="./mreg1.html">
 <span class="dropdown-text">1. Was ist eine Mehrebenenregression?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mreg2.html">
 <span class="dropdown-text">2. Wann ist eine Mehrebenenregression angebracht?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mreg3.html">
 <span class="dropdown-text">3. Wie werden die Daten für eine Mehrebenregression vorbereitet?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mreg4.html">
 <span class="dropdown-text">4. Wie schätzt man eine Mehrebenenregression in R?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mreg5.html">
 <span class="dropdown-text">5. Wie schätzt man variierende Slopes und Cross-Level Interaktionen?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./mreg6.html">
 <span class="dropdown-text">6. Wie lassen sich die Ergebnisse einer Mehrebenregression berichten?</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./ressourcen.html">
 <span class="menu-text">Ressourcen</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">Kontakt</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">4. Wie schätzt man eine Mehrebenenregression in R?</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        <div class="sidebar-tools-collapse tools-wide">
    <a href="https://www.sowi.uni-stuttgart.de/institut/team/Remer" title="" class="sidebar-tool px-1"><i class="bi bi-bank"></i></a>
    <a href="https://github.com/uweremer/mreg" title="" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="https://fediscience.org/@uweremer" title="" class="sidebar-tool px-1"><i class="bi bi-mastodon"></i></a>
</div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg1.html" class="sidebar-item-text sidebar-link">1. Was ist eine Mehrebenenregression?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg2.html" class="sidebar-item-text sidebar-link">2. Wann ist eine Mehrebenenregression angebracht?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg3.html" class="sidebar-item-text sidebar-link">3. Wie werden die Daten für eine Mehrebenregression vorbereitet?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg4.html" class="sidebar-item-text sidebar-link active">4. Wie schätzt man eine Mehrebenenregression in R?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg5.html" class="sidebar-item-text sidebar-link">5. Wie schätzt man variierende Slopes und Cross-Level Interaktionen?</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mreg6.html" class="sidebar-item-text sidebar-link">6. Wie lassen sich die Ergebnisse einer Mehrebenregression berichten?</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Auf dieser Seite</h2>
   
  <ul>
  <li><a href="#themenüberblick" id="toc-themenüberblick" class="nav-link active" data-scroll-target="#themenüberblick">Themenüberblick</a></li>
  <li><a href="#variierende-intercepts-mit-prädiktoren-auf-l1" id="toc-variierende-intercepts-mit-prädiktoren-auf-l1" class="nav-link" data-scroll-target="#variierende-intercepts-mit-prädiktoren-auf-l1">Variierende Intercepts mit Prädiktoren auf L1</a></li>
  <li><a href="#variierende-intercepts-mit-prädiktoren-auf-l1-und-l2" id="toc-variierende-intercepts-mit-prädiktoren-auf-l1-und-l2" class="nav-link" data-scroll-target="#variierende-intercepts-mit-prädiktoren-auf-l1-und-l2">Variierende Intercepts mit Prädiktoren auf L1 und L2</a></li>
  <li><a href="#schluss" id="toc-schluss" class="nav-link" data-scroll-target="#schluss">Schluss</a></li>
  <li><a href="#aufgabe" id="toc-aufgabe" class="nav-link" data-scroll-target="#aufgabe">Aufgabe</a></li>
  <li><a href="#lernzielabgleich" id="toc-lernzielabgleich" class="nav-link" data-scroll-target="#lernzielabgleich">Lernzielabgleich</a></li>
  <li><a href="#literatur" id="toc-literatur" class="nav-link" data-scroll-target="#literatur">Literatur</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">4. Wie schätzt man eine Mehrebenenregression in R?</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-layout-align="center">
<style type="text/css">
/* CSS Stil für Formeln unter Scatterplots */
P.math {
    text-align: center;
    font-size: 2vw;
}

P.math_left {
    text-align: left;
    font-size: 1.5vw;
}


DIV.border {
    padding:9.5px;
    border-radius:4px;
    border:1px solid #cccccc;
    margin-top: 10px;
    margin-bottom:10px;
}
</style>
</div>
<section id="themenüberblick" class="level1">
<h1>Themenüberblick</h1>
<p>Im vorigen <a href="./mreg2.html">Teil 2</a> haben wir gesehen, wie man mit Hilfe des sogenannten Nullmodells berechnet, ob eine Mehrebenenregression überhaupt notwendig ist. Und in <a href="./mreg3.html">Teil 3</a>, wie man die Daten für die Mehrebenenregression vorbereitet.</p>
<p>In diesem vierten Teil geht es nun darum: Wie schätzt man eine Mehrebenenregression in R? Und natürlich: wie interpretiert man die Ergebnisse?</p>
<p>Das Video finden Sie <a href="https://video.fernuni-hagen.de/Play/6089">hier</a>.</p>
<p>Dazu schätzen wir zwei grundlegende Modelle:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<ul>
<li>Ein Modell mit variierenden Intercepts mit Prädiktoren auf L1</li>
<li>Ein Modell mit variierenden Intercepts mit Prädiktoren auf L1 und L2</li>
</ul>
<p>Lernziele für dieses Video sind…</p>
<ul>
<li>dass Sie ein einfaches Mehrebenenmodell als Formel ausdrücken können</li>
<li>dass Sie wissen, wie man das einfache Mehrebenenmodell in R umsetzt</li>
<li>dass Sie die relevanten Quantities of Interest kennen und interpretieren können.</li>
</ul>
<p>Das alles schauen wir uns direkt in R an…</p>
</section>
<section id="variierende-intercepts-mit-prädiktoren-auf-l1" class="level1">
<h1>Variierende Intercepts mit Prädiktoren auf L1</h1>
<p>Bevor wir mit dem ersten Modell loslegen, führen Sie bitte das komplette RScript zu Video 3 aus (<code>RScript_mreg3.R</code> bei den <a href="./ressourcen.html">Ressourcen</a>). Mit der <code>source()</code>-Funktion können Sie das direkt aus dem neuen Script heraus aufrufen, ohne die Datei öffnen zu müssen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"./Ressourcen/RScript_mreg3.R"</span>) <span class="co">#Pfad zur Datei ggf. anpassen</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wir sehen zwar keinen Output, aber den benötigen wir auch nicht. Wir wollen nur die Objekte im Environment haben, insbesondere, den fertig vorbereiteten ESS Datensatz.</p>
<p>Kommen wir nun zum ersten Modell. Das erste Mehrebenenmodell ist ein Varying Intercept Modell mit Prädiktoren auf Ebene 1:</p>
<p>Die Form ist dieselbe wie beim Nullmodell. Allerdings enthält die Formel nun auch die Ebene 1 Prädiktoren <span class="math inline">\(x_1\)</span> bis <span class="math inline">\(x_4\)</span>.</p>
<div class="border">
<p class="math_left">
</p><p><span class="math inline">\(y_{ij} = \beta_{0j} +\)</span> <font color="red"><span class="math inline">\(\beta_{1}x_{1ij} + \beta_{2}x_{2ij} + \beta_{3}x_{3ij} + \beta_{4}x_{4ij}\)</span></font> <span class="math inline">\(+ r_{ij}\)</span></p>
<p></p>
<p>mit</p>
<p class="math_left">
</p><p><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></p>
<p></p>
</div>
<p>Statt <span class="math inline">\(x_1\)</span> bis <span class="math inline">\(x_4\)</span> könnten wir auch die entsprechenden Variablen aufführen: <code>bildung</code>, <code>responsivitaet</code>, <code>zufr_wirtschaft</code> und <code>soz_vertrauen</code>.</p>
<p>Diese setzen wir auch in der Formel in der <code>lmer()</code>-Funktion ein:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest) </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mreg1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(pol_vertrauen <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> bildung <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                responsivitaet <span class="sc">+</span> zufr_wirtschaft <span class="sc">+</span> soz_vertrauen <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                (<span class="dv">1</span> <span class="sc">|</span> cntry),  </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>ess)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mit <code>summary()</code> können wir die Ergebnisse anzeigen lassen:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mreg1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: pol_vertrauen ~ 1 + bildung + responsivitaet + zufr_wirtschaft +  
    soz_vertrauen + (1 | cntry)
   Data: ess

REML criterion at convergence: 154604

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-4.167 -0.657  0.012  0.647  5.390 

Random effects:
 Groups   Name        Variance Std.Dev.
 cntry    (Intercept) 0.147    0.384   
 Residual             2.784    1.669   
Number of obs: 39998, groups:  cntry, 25

Fixed effects:
                   Estimate  Std. Error          df t value
(Intercept)         3.92905     0.07725    23.96503   50.86
bildung            -0.02501     0.00486 39991.56791   -5.15
responsivitaet      0.84569     0.01141 39988.92072   74.09
zufr_wirtschaft     0.31301     0.00439 39651.68675   71.33
soz_vertrauen       0.21042     0.00499 39958.23593   42.15
                            Pr(&gt;|t|)    
(Intercept)     &lt; 0.0000000000000002 ***
bildung                   0.00000027 ***
responsivitaet  &lt; 0.0000000000000002 ***
zufr_wirtschaft &lt; 0.0000000000000002 ***
soz_vertrauen   &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) bildng rspnsv zfr_wr
bildung     -0.002                     
responsivtt -0.001 -0.177              
zfr_wrtschf  0.003 -0.011 -0.242       
soz_vertran  0.003 -0.104 -0.140 -0.231</code></pre>
</div>
</div>
<p>Schauen wir als erstes auf die Fixed Effects.</p>
<p>Wir sehen, dass es neben dem Intercept <span class="math inline">\(\beta_{0j}\)</span> nun auch weitere Koeffizienten gibt. Das sind die b-Koeffizienten für die unabhängigen Variablen, also <span class="math inline">\(\beta_1\)</span> bis <span class="math inline">\(\beta_4\)</span>.</p>
<p>Wie bereits beim Nullmodell ist der Intercept der Mittelwert der variierenden Intercepts $beta_{0j} - also das, was in der Regressionsgleichung mit <span class="math inline">\(\gamma_{00}\)</span> bezeichnet wurde.</p>
<p>Die anderen Regressionsparameter sind nicht variierende Regressionsparameter, und sind wie ganz normale Regressionskoeffizienten zu interpretieren:</p>
<p>Alle Variablen haben einen signifikanten Einfluss, wie wir an der letzten Spalte sehen.</p>
<p>Mit Zunahme von Bildung um einen Skalenpunkt, sinkt das politische Vertrauen um <span class="math inline">\(-0.025\)</span>.</p>
<p>Eine vorläufige Antwort auf unsere Forschungsfrage lautet also: Bildung beeinflusst das politische Vertrauen negativ.</p>
<p>Die anderen Determinanten haben einen positiven Effekt auf politisches Vertrauen. Da die wahrgenommene politische Responsivität eine andere Skalenbreite aufweist, können wir die Effektstärken jedoch nicht direkt miteinander vergleichen.</p>
<p>Schauen wir uns nun die Random Effects an.</p>
<p>Die Random Effects berichten die Varianz der Residuen der beiden Gleichungen:</p>
<div class="border">
<p class="math_left">
</p><p><span class="math inline">\(y_{ij} = \beta_{0j} + \beta_{1}x_{1ij} + \beta_{2}x_{2ij} + \beta_{3}x_{3ij} + \beta_{4}x_{4ij} + r_{ij}\)</span></p>
<p></p>
<p>mit</p>
<p class="math_left">
</p><p><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></p>
<p></p>
</div>
<p>Also: Wie groß ist die unerklärte Varianz auf Individualebene <span class="math inline">\(r_{ij}\)</span> - das finden wir in der Tabelle hier unter “Residual”. Der Wert ist <span class="math inline">\(2.784\)</span>.</p>
<p>Und wie groß ist die Varianz der variierenden Intercepts <span class="math inline">\(u_{0j}\)</span>. Also: Wie sehr streuen die Ländermittelwerte <span class="math inline">\(\beta_{0j}\)</span> um den Grand Mean <span class="math inline">\(\gamma_{00}\)</span>? Das sehen wir bei “cntry (Intercept)”. Dieser Wert ist <span class="math inline">\(0.147\)</span>.</p>
<p>Wir können uns auch anschauen, wie diese Streuung um den Grand Mean ganz konkret aussieht. Dafür gibt es die Funktion <code>ranef()</code> - sie steht für random Effects und berichtet die Werte jedes einzelnen <span class="math inline">\(\beta_{0j}\)</span> - also den jeweiligen länderspezifischen Intercept:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranef</span>(mreg1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$cntry
   (Intercept)
AT     -0.0536
BE      0.3936
BG     -0.2900
CH      0.2334
CY     -0.0587
CZ     -0.3795
DE     -0.3467
EE      0.1977
ES     -0.3705
FI      0.4898
FR      0.2963
GB     -0.1435
HR     -0.5364
HU      0.6308
IE     -0.0381
IT      0.3565
LT     -0.3225
LV     -0.3304
NL      0.6036
NO      0.3598
PL     -0.4996
PT     -0.2344
SE      0.4528
SI     -0.5826
SK      0.1719

with conditional variances for "cntry" </code></pre>
</div>
</div>
<p>Da wir zuvor alle unabhängigen Variablen an deren Grand Mean zentriert haben, sind diese länderspezifischen Intercepts als Abweichung vom Grand Mean zu interpretieren.</p>
<p>Für Belgien BE liegt der länderspezifische Intercept <span class="math inline">\(\beta_{0~Belgien}\)</span> also <span class="math inline">\(0.394\)</span> Skalenpunkte über dem fixierten Intercept bzw. Grand Mean <span class="math inline">\(\gamma_{00}\)</span> von <span class="math inline">\(3.93\)</span>.</p>
<p>Für Deutschland DE liegt er <span class="math inline">\(-0.347\)</span> Skalenpunkte <em>unter</em> diesem Wert.</p>
<p>Analog kann man sich auch die fixierten Effekte ausgeben lassen.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(mreg1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)         bildung  responsivitaet zufr_wirtschaft   soz_vertrauen 
          3.929          -0.025           0.846           0.313           0.210 </code></pre>
</div>
</div>
<p>Was uns nun noch interessiert ist, wie gut unser Modell die abhängige Variable erklärt.</p>
<p>Beim OLS-Regressionsmodell betrachten wir dafür den Determinantionskoeffizienten <span class="math inline">\(R^2\)</span> als Maß für Varianzaufklärung. Auch beim Mehrebenenmodell können wir prüfen, wie viel Varianz durch das Modell erklärt wird.</p>
<p>Im einfachsten Fall können wir berechnen, wieviel der Varianz die in den Random Effects des Nullmodells steckt, durch ein Modell mit Prädiktoren erklärt wird.</p>
<p>Berechnen wir also noch Mal auf das Nullmodell auf Basis der jetzt 25 Länder:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mreg0 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(pol_vertrauen <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> cntry),  </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>ess)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mreg0)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: pol_vertrauen ~ 1 + (1 | cntry)
   Data: ess

REML criterion at convergence: 171592

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-2.811 -0.741  0.038  0.694  3.916 

Random effects:
 Groups   Name        Variance Std.Dev.
 cntry    (Intercept) 1.11     1.05    
 Residual             4.26     2.06    
Number of obs: 39998, groups:  cntry, 25

Fixed effects:
            Estimate Std. Error     df t value           Pr(&gt;|t|)    
(Intercept)    3.892      0.211 23.996    18.4 0.0000000000000011 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">VarCorr</span>(mreg0))[,<span class="dv">4</span>]</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.11 4.26</code></pre>
</div>
</div>
<p>Auf Ebene 2, der Ebene der Länder haben wir eine Varianz von <span class="math inline">\(1.112\)</span>. Auf Individualebene eine Varianz von <span class="math inline">\(4.256\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mreg1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: pol_vertrauen ~ 1 + bildung + responsivitaet + zufr_wirtschaft +  
    soz_vertrauen + (1 | cntry)
   Data: ess

REML criterion at convergence: 154604

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-4.167 -0.657  0.012  0.647  5.390 

Random effects:
 Groups   Name        Variance Std.Dev.
 cntry    (Intercept) 0.147    0.384   
 Residual             2.784    1.669   
Number of obs: 39998, groups:  cntry, 25

Fixed effects:
                   Estimate  Std. Error          df t value
(Intercept)         3.92905     0.07725    23.96503   50.86
bildung            -0.02501     0.00486 39991.56791   -5.15
responsivitaet      0.84569     0.01141 39988.92072   74.09
zufr_wirtschaft     0.31301     0.00439 39651.68675   71.33
soz_vertrauen       0.21042     0.00499 39958.23593   42.15
                            Pr(&gt;|t|)    
(Intercept)     &lt; 0.0000000000000002 ***
bildung                   0.00000027 ***
responsivitaet  &lt; 0.0000000000000002 ***
zufr_wirtschaft &lt; 0.0000000000000002 ***
soz_vertrauen   &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) bildng rspnsv zfr_wr
bildung     -0.002                     
responsivtt -0.001 -0.177              
zfr_wrtschf  0.003 -0.011 -0.242       
soz_vertran  0.003 -0.104 -0.140 -0.231</code></pre>
</div>
</div>
<p>In unserem Modell <code>mreg1</code> ist die Varianz der Intercepts nur noch bei <span class="math inline">\(0.147\)</span> und die Residualvarianz auf Individualebene bei <span class="math inline">\(2.784\)</span></p>
<p>Also auf Ebene 1 bleiben nur noch <span class="math inline">\(\frac{2.784}{4.256}=0.654\)</span>, also 65.4 Prozent der Varianz übrig.</p>
<p>Oder anders ausgedrückt: Wir erklären 34.6 Prozent der Varianz auf Ebene 1.</p>
<p>Das können wir auch allgemeiner ausdrücken:</p>
<p><span class="math inline">\(R^2_{L1}=1-\frac{s^2_{L1_{Modell}}}{s^2_{L1_{Nullmodell}}}\)</span></p>
<p>Und wir können auch für Ebene 2 berechnen, wieviel der im Nullmodell auf Ebene 2 vorhandenen Varianz durch unser Modell mit Prädiktoren erklärt wurde.</p>
<p><span class="math inline">\(R^2_{L2}=1-\frac{s^2_{L2_{Modell}}}{s^2_{L2_{Nullmodell}}}\)</span></p>
<p>Das sind <span class="math inline">\(1-\frac{0.147}{1.112}=0.868\)</span>- also 86.8 Prozent der Varianz auf Ebene 2 werden durch unser Modell <code>mreg1</code> bereits erklärt.</p>
<p>“Moment!” werden Sie jetzt sagen! Wie soll das denn gehen! Wir haben doch nur Prädiktoren der Individualebene im Modell! Wie können individuelle Merkmale von Befragten Varianz zwischen den Ländern erklären?</p>
<p>Richtig! Das ist eine gute Frage. Drücken Sie Pause und nehmen Sie sich ein paar Minuten um zu überlegen, was der Grund sein könnte.</p>
<p>Gut, hier kommt die Auflösung: Es handelt sich um sogenannte <strong>Kompositionseffekte</strong>.</p>
<p>Nehmen wir Beispielsweise unsere unabhängige Variable <em>Zufriedenheit mit der Wirtschaftslage</em>. Das ist eine Variable der Individualebene und die Befragten in den Ländern können unterschiedliche Werte auf dieser Variable einnehmen. Es ist kein Kontextmerkmal, dass für alle Befragten eines Landes gleich ist.</p>
<p>Aber: Wenn viele oder im Extremfall alle Individuen eines Landes besonders hohe Werte auf dieser Variable einnehmen , dagegen in einem anderen Land viele Individuen eine sehr geringe Zufriedenheit mit der Wirtschaft aufweisen, dann wird - wenn diese Variable auch einen Einfluss auf das politische Vertrauen hat - allein durch die Zusammensetzung der Gruppen das durchschnittliche Niveau der abhängigen Variable in den Ländern beeinflusst.</p>
<p>Also dadurch, dass sich die Länder hinsichtlich der Zusammensetzung der Individuen und ihrer Merkmale unterscheiden, wird bereits Varianz zwischen den Ländern erklärt. Denn mit durchschnittlich höherer Zufriedenheit mit der Wirtschaft geht ja auch durchschnittlich höheres politisches Vertrauen einher.</p>
<p>Somit kann also die Zusammensetzung der Individuen hinsichtlich ihrer Merkmale auf Ebene 1 als Kompositionseffekt Varianz auf Ebene 2, also zwischen den Ländern erklären.</p>
<p>So simpel und klar die Berechnung und Interpretation dieser <span class="math inline">\(R^2\)</span> Maße für die beiden Ebenen auch ist: Wenn die Modelle komplexer werden und später mehr als nur ein random Effect (also mehr als nur ein variierender Intercept) vorliegt, dann kann man diese ebenenspezifischen <span class="math inline">\(R^2\)</span> nicht mehr nutzen.</p>
<p><a href="https://doi.org/10.1111/j.2041-210x.2012.00261.x">Nakagawa/Schielzeth 2012</a> haben noch weitere Nachteile angeführt und schlagen eine Alternative Berechnung für ein <span class="math inline">\(R^2\)</span> für Mehrebenenregressionen vor.</p>
<p>Wir können <span class="math inline">\(Nakagawa~R^2\)</span> mit Hilfe des <a href="https://cran.r-project.org/web/packages/performance/index.html"><code>performance</code></a>-Paketes und der Funktion <code>r2()</code> berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(mreg1)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Mixed Models

  Conditional R2: 0.448
     Marginal R2: 0.419</code></pre>
</div>
</div>
<p>Das marginale <span class="math inline">\(R^2\)</span> können wir dabei ignorieren, da es die Varianzen der Random Effects nicht berücksichtigt. Stattdessen betrachten wir das konditionale <span class="math inline">\(R^2\)</span>.</p>
<p>Unser Modell erklärt also etwa 44.8 Prozent der Varianz in den Daten.</p>
<p>Darüber hinaus bietet das <a href="https://cran.r-project.org/web/packages/performance/index.html"><code>performance</code></a>-Paket die Möglichkeit mit der Funktion <code>model_performance()</code> bei Bedarf weitere Goodness of Fit Maße zu berechnen:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_performance</span>(mreg0)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC       |      AICc |       BIC | R2 (cond.) | R2 (marg.) |   ICC |  RMSE | Sigma
-----------------------------------------------------------------------------------
1.716e+05 | 1.716e+05 | 1.716e+05 |      0.207 |      0.000 | 0.207 | 2.062 | 2.063</code></pre>
</div>
</div>
<p>Kommen wir nun zum nächsten Schritt.</p>
</section>
<section id="variierende-intercepts-mit-prädiktoren-auf-l1-und-l2" class="level1">
<h1>Variierende Intercepts mit Prädiktoren auf L1 und L2</h1>
<p>Wir ergänzen das Modell nun um unseren Prädiktor auf Ebene 2.</p>
<p>Als zweite Forschungsfrage wollen wir wissen, ob das Ausmaß an Korruption in einem Land den Effekt von Bildung beeinflussen kann.</p>
<p>Wir nehmen also den <em>Corruption Perception Index</em> (CPI) von Transparency International mit ins Model. Der CPI ist eine Skala von 0 ‘sehr korrupt’ bis 100 ‘sehr sauber’.</p>
<p>Nochmal zur Erinnerung, es ist ein Expertenrating, daher wird der Index <em>Corruption Perception Index</em> genannt. 100 steht nicht für keine objektive Korruption, sondern Transparency International nennt es dann ‘sehr sauber’.</p>
<p>Damit wir die Effekte später intuitiver Interpretieren können, drehen wir die Variable CPI, famit höhere Werte, höhere Korruption bedeuten.</p>
<p>Die original Variable heißt <code>c_ticpi_2018</code>. Diese wird gedreht, dann schauen wir uns die Verteilung mit einer Grafik an.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ess<span class="sc">$</span>korruption <span class="ot">&lt;-</span> <span class="fu">abs</span>(ess<span class="sc">$</span>c_ticpi_2018<span class="dv">-100</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ess, <span class="fu">aes</span>(<span class="at">x=</span>cntry, <span class="at">y=</span>korruption)) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> <span class="st">"mean"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">6</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="mreg4_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Da die Variable auf Ebene 2 liegt, kann sie nur den länderspezifischen Mittelwert der abhängigen Variable beeinflussen.</p>
<p>Die länderspezifische Korruption muss also Teil der Gleichung des variierenden Intercepts <span class="math inline">\(\beta_{0j}\)</span> sein. Wir ergänzen dafür die Koeffizienten <font color="red"><span class="math inline">\(\gamma_{01j}\)</span></font> in der zweiten Zeile der Gleichung:</p>
<div class="border">
<p class="math_left">
</p><p><span class="math inline">\(y_{ij} = \beta_{0j} + \beta_{1}x_{1ij} + \beta_{2}x_{2ij} + \beta_{3}x_{3ij} + \beta_{4}x_{4ij} + r_{ij}\)</span></p>
<p></p>
<p>mit</p>
<p class="math_left">
</p><p><span class="math inline">\(\beta_{0j} = \gamma_{00} +\)</span> <font color="red"><span class="math inline">\(\gamma_{01j}\)</span></font> <span class="math inline">\(+ u_{0j}\)</span></p>
<p></p>
</div>
<p><font color="red"><span class="math inline">\(\gamma_{01j}\)</span></font> ist also Regressionskoeffizient für den Einfluss der Variable <code>korruption</code> auf den variierenden Intercept.</p>
<p>Durch die Aufnahme dieser unabhängigen Variable auf Ebene 2 sollte zuvor unerklärte Varianz auf Ebene 2 geringer werden - also das Ebene 2 Residuum <span class="math inline">\(u_{0j}\)</span> geringer werden.</p>
<p>Ob das so ist, sehen wir gleich.</p>
<p>Im R Befehl für die Mehrebenenregression müssen wir nicht explizit angeben, dass es sich um eine Kontextvariable handelt. Wir ergänzen sie einfach in der Formel wie jede andere Variable auch.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest) </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mreg2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(pol_vertrauen <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> bildung <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                responsivitaet <span class="sc">+</span> zufr_wirtschaft <span class="sc">+</span> soz_vertrauen <span class="sc">+</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                korruption <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                (<span class="dv">1</span> <span class="sc">|</span> cntry),  </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>ess)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mreg2)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: pol_vertrauen ~ 1 + bildung + responsivitaet + zufr_wirtschaft +  
    soz_vertrauen + korruption + (1 | cntry)
   Data: ess

REML criterion at convergence: 154608

Scaled residuals: 
   Min     1Q Median     3Q    Max 
-4.162 -0.657  0.012  0.646  5.391 

Random effects:
 Groups   Name        Variance Std.Dev.
 cntry    (Intercept) 0.127    0.357   
 Residual             2.784    1.669   
Number of obs: 39998, groups:  cntry, 25

Fixed effects:
                   Estimate  Std. Error          df t value
(Intercept)         4.32173     0.19373    23.15747   22.31
bildung            -0.02499     0.00486 39991.73816   -5.14
responsivitaet      0.84524     0.01142 39991.67508   74.04
zufr_wirtschaft     0.31270     0.00439 39865.03534   71.23
soz_vertrauen       0.21016     0.00499 39991.84797   42.08
korruption         -0.01176     0.00539    23.23182   -2.18
                            Pr(&gt;|t|)    
(Intercept)     &lt; 0.0000000000000002 ***
bildung                   0.00000027 ***
responsivitaet  &lt; 0.0000000000000002 ***
zufr_wirtschaft &lt; 0.0000000000000002 ***
soz_vertrauen   &lt; 0.0000000000000002 ***
korruption                     0.039 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) bildng rspnsv zfr_wr sz_vrt
bildung      0.002                            
responsivtt -0.021 -0.177                     
zfr_wrtschf -0.034 -0.011 -0.241              
soz_vertran -0.027 -0.104 -0.140 -0.230       
korruption  -0.929 -0.003  0.022  0.037  0.030</code></pre>
</div>
</div>
<p>Wie wir bei den Fixed Effects sehen können, hat also Korruption einen kleinen, aber signifikanten negativen Effekt auf den variierenden Intercept. Also mit Zunahme der Korruption um einen Skalenpunkt sinkt das durchschnittliche politische Vertrauen in einem Land um <span class="math inline">\(-0.012\)</span></p>
<p>Da der Korruptionsindex eine Skala von 0 bis 100 ist, ist das nicht wenig. Sehr korruptionsbelastete Länder haben einen Korruptionsindex von über 50. Am anderen Ende stehen Länder mit einem Wert von 15. Bei 35 Skalenpunkten Unterschied ergibt sich also für die abhängige Variable politisches Vertrauen einen Unterschied von <span class="math inline">\(-0.412\)</span> Punkten.</p>
<p>Und was sagt die Modellgüte?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">model_performance</span>(mreg2)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC       |      AICc |       BIC | R2 (cond.) | R2 (marg.) |   ICC |  RMSE | Sigma
-----------------------------------------------------------------------------------
1.546e+05 | 1.546e+05 | 1.547e+05 |      0.471 |      0.446 | 0.044 | 1.668 | 1.669</code></pre>
</div>
</div>
<p>Das konditionale <span class="math inline">\(R^2\)</span> erhöht sich minimal von 44.8 auf 47.1.</p>
</section>
<section id="schluss" class="level1">
<h1>Schluss</h1>
<p>Damit sind wir am Ende des vierten Videos.</p>
<p>Wir haben gesehen, wie man ein einfaches Mehrebenenmodell als Formel notiert und das Modell mit der <code>lmer()</code>-Funktion in R umsetzt.</p>
<p>Dabei haben wir zuerst ein variierendes Intercept Modell mit Prädiktoren auf Ebene 1 geschätzt und habe Kompositionseffekte kennengelernt. Danach haben wir das Modell um eine unabhängige Variable auf Ebene 2 ergänzt und interpretiert.</p>
<p>Im nächsten <a href="./mreg5.html">Video 5</a> werden wir dann das Varying Slope Modell und das Modell mit Cross-Level Interaktion anschauen und klären, wie man herausfindet, welches Modell das passende ist.</p>
<p>Am Ende dieses Videos gibt es noch eine Aufgabe und zum Schluss die Literatur.</p>
</section>
<section id="aufgabe" class="level1">
<h1>Aufgabe</h1>
<ul>
<li>Rechnen Sie zu einer eigenen Fragestellung ein Mehrebenenmodell mit Prädiktoren auf Ebene 1. Prüfen Sie, wie stark Kompositionseffekte die Varianz auf Ebene 2 im Vergleich zum Nullmodell verringern.</li>
<li>Ergänzen Sie das Mehrebenenmodell um Prädiktoren auf Ebene 2. Wie viel Varianz können Sie auf den beiden Ebenen jeweils für sich genommen erklären?</li>
</ul>
</section>
<section id="lernzielabgleich" class="level1">
<h1>Lernzielabgleich</h1>
<p>Haben Sie alles mitgenommen? Fragen Sie sich selbst, ob Sie die folgenden Lernziele erreicht haben:</p>
<ul>
<li>Sie können ein einfaches Mehrebenenmodell als Formel ausdrücken.</li>
<li>Sie wissen, wie man das einfache Mehrebenenmodell in R umsetzt.</li>
<li>Sie kennen die relevanten Quantities of Interest und können sie interpretieren.</li>
</ul>
</section>
<section id="literatur" class="level1">
<h1>Literatur</h1>
<ul>
<li>Nakagawa, S.; Schielzeth, H. (2013): A general and simple method for obtaining R2 from generalized linear mixed-effects models. Methods in Ecology and Evolution, 4(2), 133–142. DOI: <a href="https://doi.org/10.1111/j.2041-210x.2012.00261.x" class="uri">https://doi.org/10.1111/j.2041-210x.2012.00261.x</a></li>
</ul>
<p><img src="https://vg08.met.vgwort.de/na/6671fcafb6f8454eae70c465213a0d82" width="1" height="1" alt=""></p>
<div class="cell" data-layout-align="center">

</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Fußnoten</h2>

<ol>
<li id="fn1"><p>In <a href="./mreg5.html">Teil 5</a> erweitern wir dann diese Modelle um variierenden Slopes und Cross-Level-Interaktionen.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/^(?:http:|https:)\/\.github\.io\/uweremer/);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© 2022, Uwe Remer</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="./datenschutz.html">Datenschutz</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="./about.html">Impressum</a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>